# Generated by Django 5.1.5 on 2025-02-05 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(max_length=20, verbose_name='Subscription Name')),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('billing_duration', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF YEARLY', 'Half Yearly'), ('YEARLY', 'Yearly')], max_length=50, null=True, verbose_name='Billing Duration')),
            ],
            options={
                'ordering': ['-subscription_name', '-billing_duration'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(help_text='Please, enter your first name', max_length=20)),
                ('lastName', models.CharField(help_text='Please, enter your last name', max_length=20)),
                ('username', models.CharField(help_text='Please, enter your username', max_length=20, unique=True)),
                ('password', models.CharField(help_text='Please, enter your password', max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('dob', models.DateField(help_text='Please, enter your date of birth', verbose_name='Date of Birth')),
                ('date_of_registration', models.DateTimeField(auto_now=True, verbose_name='Date of Registration')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Subscription payment')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.subscription')),
            ],
            options={
                'ordering': ['-lastName', '-firstName'],
            },
        ),
    ]
