# Generated by Django 5.1.5 on 2025-02-10 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, verbose_name='Class Name')),
                ('class_date', models.DateField(verbose_name='Class Date')),
                ('class_time', models.TimeField(verbose_name='Class Time')),
                ('description', models.CharField(help_text='Please, enter class description', max_length=500)),
                ('space', models.CharField(help_text='Please, enter where the class will be located', max_length=50)),
            ],
            options={
                'ordering': ['-class_date', '-class_time'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['lastName', 'firstName']},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='discount',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_payment',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of Payment'),
        ),
        migrations.AddField(
            model_name='user',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_signed_in',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Signed In'),
        ),
        migrations.AddField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of Modified'),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_method',
            field=models.CharField(blank=True, help_text="Please enter user's payment method", max_length=100, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_registration',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of Registration'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Subscription Payment'),
        ),
        migrations.AddField(
            model_name='user',
            name='classes_booked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.classes'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=50, verbose_name='Name of the trainer')),
                ('trainer_classes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.classes')),
            ],
            options={
                'ordering': ['-trainer_name'],
            },
        ),
        migrations.AddField(
            model_name='classes',
            name='trainer_name',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.RESTRICT, to='users.staff'),
        ),
    ]
