# Generated by Django 5.1.5 on 2025-02-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_phone_number_staff_hiring_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='triner_phone_number',
            new_name='trainer_phone_number',
        ),
    ]
