# Generated by Django 5.1.5 on 2025-02-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_customuser_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-billing_duration'], 'verbose_name_plural': 'Subscription'},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_name',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_duration',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('3MONTHS', '3Months'), ('HALF YEARLY', 'Half Yearly'), ('YEARLY', 'Yearly')], max_length=20, null=True, verbose_name='Billing Duration'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CARD', 'Card'), ('CASH', 'Cash'), ('INSTALLMENTS', 'Installments')], max_length=20, null=True, verbose_name='Payment Method'),
        ),
    ]
